apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
spec:
  serviceName: postgres-slave
  replicas: 1
  selector:
    matchLabels:
      app: postgres-slave
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value: MySecretStringSlave
        - name: POSTGRES_MASTER_HOST
          value: postgres-master
        - name: POSTGRES_MASTER_PORT
          value: "5432"
        - name: POSTGRES_REPLICATION_USER
          value: postgres
        - name: POSTGRES_REPLICATION_PASSWORD
          value: MySecretStringMaster
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
spec:
  selector:
    app: postgres-slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-srv
spec:
  type: NodePort
  selector:
    app: postgres-slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32223


   